ブロック崩し作成
natsukikokubu/block-breaker pull request #1
Opened 2023-06-08 13:33 UTC by natsukikokubu

## 概要

ブロック崩しゲーム

## 変更点

ブロック崩しゲームを新規作成しました

## 動作確認手順

- [ ] --を開く
- [ ] --をすると、--になる
- [ ] ...

2023-06-12 08:17 UTC, tachibanayu24 commented
@natsukikokubu 
動作確認手順を埋めて re-review requestしてください。
動作確認手順とは、「このように動作することが確認できれば、挙動という観点からはコードの正しさをざっくり保証できる」という意味のものです

2023-06-16 14:05 UTC, natsukikokubu commented
@tachibanayu24 
動作確認手順を書いたのでレビューをお願いします！

2023-06-16 14:35 UTC, tachibanayu24 requested changes
@natsukikokubu 
ひとまず目についたものをコメントしましたが、このrepoはこんなもので良いです。
FB箇所を修正できたら、 re-review requestください 🙏

2023-06-16 14:35 UTC, tachibanayu24 commented on background.js
> +  constructor() {}
この何もしないコンストラクトは不要では

2023-06-16 14:35 UTC, tachibanayu24 commented on background.js
> +class BackGround {
backgroundは一般にこれで位置単語であり、 back groundではありません
なので以下のようにします

```suggestion
class Background {
```

2023-06-16 14:35 UTC, tachibanayu24 commented on background.js
> +  Draw(context) {
一般的に関数はローワーキャメルケースで命名します。
他の箇所についても同様です。

```suggestion
  draw(context) {
```

2023-06-16 14:35 UTC, tachibanayu24 commented on background.js
> +  Collision(left, right, top, bottom) {
例えばロジックの途中で注釈したい場合などはいいんですが、このようにクラスのメンバー関数などの場合は、以下のようにコメントすると良いです。
これをJSDocと言います。

こうすると、他のファイルからでもマイスオーバーでコードヒントが効いて便利です。

<img width="708" alt="Screenshot 2023-06-16 at 23 18 30" src="https://github.com/natsukikokubu/block-breaker/assets/23476543/a3bb4e9d-b2b6-4d61-993b-7465e0806cc9">

2023-06-16 14:35 UTC, tachibanayu24 commented on ball.js
> +    this.move_y = 0;
jsの世界ではsnake_caseは変数名として利用しないことが一般的です
また、特に理由がない場合は省略形を避けることがベターです。

positionXやmoveXなどとしましょう

2023-06-16 14:35 UTC, tachibanayu24 commented on ball.js
> +  }
classにはアクセサーという機能があり、getterやsetterを明示的に宣言することができるので、メンバー関数ではなくこの機能を利用するべきです
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/get
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/set

ただ、難しければ今は対応しなくてもいいです。
こういうものがあるんだ、くらいで

2023-06-16 14:35 UTC, tachibanayu24 commented on ball.js
> +  //球のバウンディングボックス
```suggestion
  // 球のバウンディングボックス
```

半角スペースを入れる

2023-06-16 14:35 UTC, tachibanayu24 commented on block.js
> +    let block_colum_max = 10;
再代入しない場合は必ず const を利用してください。
letを使ったほうがいいのは限定的なケースのみと認識してください。

仮にletを使わないといけない場合は、letを使わない方法はないか？と考えるくらいで今はちょうどいいかもしれません

2023-06-16 14:35 UTC, tachibanayu24 commented on block.js
> +    ];
tableという語は適切ではないかと思います。
blockColors とかでいいかと。
配列は複数形、または hogeList と表すことが一般的です。

2023-06-16 14:35 UTC, tachibanayu24 commented on block.js
> +    }
このようなネストの深い複雑なコードは、コメントアウトで注釈してあげると親切です。

2023-06-16 14:35 UTC, tachibanayu24 commented on gamemanager.js
> +class GameManager {
ファイル名は
gameManeger.js ですかね

2023-06-16 14:35 UTC, tachibanayu24 commented on background.js
> +class BackGround {
すべてのクラスに、このクラスは何に関心を持っていて、どのような責務があるのかをコメントで書きましょう。
backgroundは背景を表現するクラスで、背景の描画やボールの衝突判定をしていると思います。

2023-06-16 14:35 UTC, tachibanayu24 commented on main.js
> +//-------------------------------------------------------
こういうコメントの書き方はしないので、JSDocで書いてください。

2023-06-17 13:36 UTC, natsukikokubu commented on background.js
> +  Draw(context) {
承知しました。
全て修正するのは時間を割いてしまうので、次回から気をつけます。

2023-06-18 06:56 UTC, natsukikokubu commented on background.js
> +  Collision(left, right, top, bottom) {
何箇所かJSDocしました。今後は全てJSDocを使えるようにします。ご確認お願い致します。

2023-06-22 13:55 UTC, natsukikokubu commented
@tachibanayu24 
上記の指示を頂いた箇所をできる範囲で修正をしたので、再レビューをお願いします。

2023-06-22 14:06 UTC, tachibanayu24 requested changes
@natsukikokubu 
全体的に良いと思います！
軽微なコメントをしていますので、修正できたら再レビュー依頼してください

2023-06-22 14:06 UTC, tachibanayu24 commented on main.js
> +マウスを右に動かすとボールは右に動く左に動かすとボールは左に動く*/
コメントの書き方が一般的なものと少し違いますね、以下のようにしてください。

```
/**
 * マウス移動
 * マウスを右に動かすとボールは右に動く左に動かすとボールは左に動く
 */
```

1行に収めたい場合は以下です
```
/** マウスボタン解放 */
```

2023-06-22 14:06 UTC, tachibanayu24 commented on ball.js
> +/**ボールを表現するクラス。
句点の有無とか、そういう最低限の体裁の統一はしましょう

2023-06-22 14:07 UTC, tachibanayu24 commented on background.js
> +  Draw(context) {
はい、一旦ここでは全部はやらなくていいです

2023-06-22 14:08 UTC, tachibanayu24 commented on background.js
> +  Collision(left, right, top, bottom) {
@natsukikokubu 
すべてやってくださいと行っているわけではなく、「よそのファイルから参照される可能性がある部分はやると親切ですよ」というだけなので、全然 `//` のコメントも併用していいです。
まあこの辺は感覚掴んでいっていただければ。

2023-06-22 14:17 UTC, tachibanayu24 commented on block.js
> +    }
コメントが少し微妙かも。
関数など、オブジェクトに対してコメントをするときは、先頭に書くとかでもいいですが、
このように何らかのロジックに対してコメントを書くときは、コメントの下の処理に対する注釈を書いていくべきですね。
あえてめちゃくちゃコメントを書くとすると以下のような感じ。

```suggestion
    // 二重ループで、blockの縦 x 横の階数ループする
    for (let y = 0; y < block_row_max; y++) {
      for (let x = 0; x < block_colum_max; x++) {
        // blockColorsから一つ色を選択して、バラバラのいろを入れる
        let color = blockColors[color_index];
        // 色がばらばらになるようにインクリメントする
        color_index++;
        // color_indexがblockColorsの最後まで行ったらリセットして最初から色をいれていく
        if (color_index >= blockColors.length) {
          color_index = 0;
        }

        // 得られたcolorをもとにBlockインスタンスを生成する
        let tmp = new Block(posX, posY, color);
        // blockに詰める
        blocks.push(tmp);
        // x軸方向の位置を、詰めたブロックの横幅分ずらす
        posX += block_width;
      }
      // x軸方向の位置を、詰めたブロックの縦幅分分ずらす
      posY += block_height;
      // 内部のforから抜けたということは、一行ぶん終わったということなので、xの位置をリセットする
      posX = 0;
    }
```

2023-06-22 15:19 UTC, natsukikokubu commented on block.js
> +    }
@tachibanayu24 
修正しました！👀　ご確認お願いします👀

2023-06-23 00:45 UTC, tachibanayu24 approved these changes
LGTM 👍

2023-06-23 00:45 UTC, tachibanayu24 commented
@natsukikokubu マージしてください

2023-06-23 07:56 UTC, merged